### ISSUE TITLE
How can you get the result in data08

### ISSUE THREAD

**Issue by hzfGuardian** [mingfeisun/COMP5421_Proj4#1]
Dear, 

I'd like to know about how you got the final result in photo/artifact/, including noRefined08.fig and refined08.fig, as simply run the program it doesn't seem to show such result. 

Or have you adjusted any parameters like lambda, sigma or any others? 

Thanks.

**Comment by mingfeisun** [comment]
Thanks for your interest,

Actually, if I remembered correctly, I didn't upload the final version to
the repo. This code is what I got from another student. I implemented this
project in C++, and posted the matlab code only for my reference.

Hope the matlab code can help you understand the idea.
